const palavras =[
   "magia",
    "torneio",
    "dragao",
    "fogo",
    "escola",
    "misterio",
    "feitico",
    "medalha",
    "amigo",
    "perigo",
    "tribruxo",
    "capa",
    "vidente",
    "po",
    "copa",
];

const dicas = [
    "É o que os bruxos e bruxas usam para realizar feitiços e encantamentos.",
    "Evento competitivo que envolve desafios perigosos e é a principal trama do livro.",
    "Criatura mágica que Harry enfrenta em uma das tarefas do torneio.",
    "Elemento que está presente em várias partes do torneio, incluindo a luta contra o dragão.",
    "O local onde Harry e seus amigos estudam magia e onde o torneio é realizado.",
    "Algo que precisa ser resolvido, especialmente em relação ao que está acontecendo com Lord Voldemort.",
    "Palavras mágicas usadas pelos bruxos para realizar magia.",
    "Prêmio que os campeões do torneio recebem como reconhecimento por seus feitos.",
    "Pessoa próxima a Harry que o ajuda e apoia durante suas aventuras.",
    "Sentimento constante durante o torneio, devido aos desafios e ameaças que enfrentam.",
    "Nome do torneio que reúne campeões de três escolas de magia.",
    "Item mágico que pode tornar quem a usa invisível.",
    "Pessoa que tem a habilidade de ver o futuro ou o que está escondido.",
    "Substância usada para várias finalidades mágicas, incluindo a transformação.",
    "Troféu que é concedido ao vencedor do torneio.",
];